package gg.rsmod.plugins.content.skills

import gg.rsmod.plugins.api.cfg.Items
import gg.rsmod.plugins.api.cfg.Npcs

enum class Skillcapes(
    val npcId: Int,
    val untrimmedCape: Int,
    val trimmedCape: Int,
    val hood: Int,
) {
    ATTACK(Npcs.AJJAT, Items.ATTACK_CAPE, Items.ATTACK_CAPE_T, Items.ATTACK_HOOD),
    DEFENCE(Npcs.MELEE_INSTRUCTOR, Items.DEFENCE_CAPE, Items.DEFENCE_CAPE_T, Items.DEFENCE_HOOD),
    STRENGTH(Npcs.SLOANE, Items.STRENGTH_CAPE, Items.STRENGTH_CAPE_T, Items.STRENGTH_HOOD),
    CONSTITUTION(
        Npcs.SURGEON_GENERAL_TAFANI,
        Items.CONSTITUTION_CAPE,
        Items.CONSTITUTION_CAPE_T,
        Items.CONSTITUTION_HOOD,
    ),
    RANGED(Npcs.ARMOUR_SALESMAN, Items.RANGING_CAPE, Items.RANGING_CAPE_T, Items.RANGING_HOOD),
    PRAYER(Npcs.BROTHER_JERED, Items.PRAYER_CAPE, Items.PRAYER_CAPE_T, Items.PRAYER_HOOD),
    MAGIC(Npcs.ROBE_STORE_OWNER, Items.MAGIC_CAPE, Items.MAGIC_CAPE_T, Items.MAGIC_HOOD),
    COOKING(Npcs.HEAD_CHEF, Items.COOKING_CAPE, Items.COOKING_CAPE_T, Items.COOKING_HOOD),
    WOODCUTTING(Npcs.WILFRED, Items.WOODCUTTING_CAPE, Items.WOODCUT_CAPE_T, Items.WOODCUTTING_HOOD),
    FLETCHING(Npcs.HICKTON, Items.FLETCHING_CAPE, Items.FLETCHING_CAPE_T, Items.FLETCHING_HOOD),
    FISHING(Npcs.MASTER_FISHER, Items.FISHING_CAPE, Items.FISHING_CAPE_T, Items.FISHING_HOOD),
    FIREMAKING(Npcs.IGNATIUS_VULCAN, Items.FIREMAKING_CAPE, Items.FIREMAKING_CAPE_T, Items.FIREMAKING_HOOD),
    CRAFTING(Npcs.MASTER_CRAFTER, Items.CRAFTING_CAPE, Items.CRAFTING_CAPE_T, Items.CRAFTING_HOOD),
    SMITHING(Npcs.THURGO, Items.SMITHING_CAPE, Items.SMITHING_CAPE_T, Items.SMITHING_HOOD),
    MINING(Npcs.DWARF_3295, Items.MINING_CAPE, Items.MINING_CAPE_T, Items.MINING_HOOD),
    HERBLORE(Npcs.KAQEMEEX, Items.HERBLORE_CAPE, Items.HERBLORE_CAPE_T, Items.HERBLORE_HOOD),
    AGILITY(Npcs.CAPN_IZZY_NOBEARD, Items.AGILITY_CAPE, Items.AGILITY_CAPE_T, Items.AGILITY_HOOD),
    THIEVING(Npcs.MARTIN_THWAIT, Items.THIEVING_CAPE, Items.THIEVING_CAPE_T, Items.THIEVING_HOOD),
    SLAYER(Npcs.KURADAL, Items.SLAYER_CAPE, Items.SLAYER_CAPE_T, Items.SLAYER_HOOD),
    FARMING(Npcs.MARTIN_THE_MASTER_GARDENER, Items.FARMING_CAPE, Items.FARMING_CAPE_T, Items.FARMING_HOOD),
    RUNECRAFTING(Npcs.LARRIAR, Items.RUNECRAFT_CAPE, Items.RUNECRAFT_CAPE_T, Items.RUNECRAFTING_HOOD),
    HUNTER(Npcs.HUNTING_EXPERT, Items.HUNTER_CAPE, Items.HUNTER_CAPE_T, Items.HUNTER_HOOD),
    CONSTRUCTION(Npcs.ESTATE_AGENT, Items.CONSTRUCT_CAPE, Items.CONSTRUCT_CAPE_T, Items.CONSTRUCT_HOOD),
    SUMMONING(Npcs.PIKKUPSTIX, Items.SUMMONING_CAPE, Items.SUMMONING_CAPE_T, Items.SUMMONING_HOOD),
    DUNGEONEERING(
        Npcs.THOK_MASTER_OF_DUNGEONEERING,
        Items.DUNGEONEERING_CAPE,
        Items.DUNGEONEERING_CAPE_T,
        Items.DUNGEONEERING_HOOD,
    ),
}
