package gg.rsmod.plugins.content.skills.mining

import gg.rsmod.plugins.content.skills.mining.Mining.Rock

private val ROCKS = setOf(
    Rock(RockType.COPPER, obj = Objs.ROCKS_2090),
    Rock(RockType.COPPER, obj = Objs.ROCKS_2091),
    Rock(RockType.IRON, obj = Objs.ROCKS_2092),
    Rock(RockType.IRON, obj = Objs.ROCKS_2093),
    Rock(RockType.IRON, obj = Objs.ROCKS_37307),
    Rock(RockType.IRON, obj = Objs.ROCKS_37309),
    Rock(RockType.SILVER, obj = Objs.ROCKS_2094),
    Rock(RockType.SILVER, obj = Objs.ROCKS_2095),
    Rock(RockType.COAL, obj = Objs.ROCKS_2096),
    Rock(RockType.COAL, obj = Objs.ROCKS_2097),
    Rock(RockType.GOLD, obj = Objs.ROCKS_2098),
    Rock(RockType.GOLD, obj = Objs.ROCKS_2099),
    Rock(RockType.SILVER, obj = Objs.ROCKS_2100),
    Rock(RockType.SILVER, obj = Objs.ROCKS_2101),
    Rock(RockType.MITHRIL, obj = Objs.ROCKS_2102),
    Rock(RockType.MITHRIL, obj = Objs.ROCKS_2103),
    Rock(RockType.ADAMANTITE, obj = Objs.ROCKS_2104),
    Rock(RockType.ADAMANTITE, obj = Objs.ROCKS_2105),
    Rock(RockType.COPPER, obj = Objs.ROCKS_3027),
    Rock(RockType.TIN, obj = Objs.ROCKS_3038),
    Rock(RockType.COAL, obj = Objs.ROCKS_3227),
    Rock(RockType.COPPER, obj = Objs.ROCKS_3229),
    Rock(RockType.GOLD, obj = Objs.ROCKS_10574),
    Rock(RockType.GOLD, obj = Objs.ROCKS_10575),
    Rock(RockType.CLAY, obj = Objs.ROCKS_10576),
    Rock(RockType.CLAY, obj = Objs.ROCKS_10577),
    Rock(RockType.CLAY, obj = Objs.ROCKS_10579),
    Rock(RockType.COAL, obj = Objs.ROCKS_10580),
    Rock(RockType.COAL, obj = Objs.ROCKS_11557),
    Rock(RockType.COAL, obj = Objs.ROCKS_11930),
    Rock(RockType.COAL, obj = Objs.ROCKS_11931),
    Rock(RockType.COAL, obj = Objs.ROCKS_11932),
    Rock(RockType.TIN, obj = Objs.ROCKS_11933),
    Rock(RockType.TIN, obj = Objs.ROCKS_11934),
    Rock(RockType.TIN, obj = Objs.ROCKS_11935),
    Rock(RockType.COPPER, obj = Objs.ROCKS_11936),
    Rock(RockType.COPPER, obj = Objs.ROCKS_11937),
    Rock(RockType.COPPER, obj = Objs.ROCKS_11938),
    Rock(RockType.ADAMANTITE, obj = Objs.ROCKS_11939),
    Rock(RockType.ADAMANTITE, obj = Objs.ROCKS_11941),
    Rock(RockType.MITHRIL, obj = Objs.ROCKS_11942),
    Rock(RockType.MITHRIL, obj = Objs.ROCKS_11943),
    Rock(RockType.MITHRIL, obj = Objs.ROCKS_11944),
    Rock(RockType.MITHRIL, obj = Objs.ROCKS_11946),
    Rock(RockType.MITHRIL, obj = Objs.ROCKS_11947),
    Rock(RockType.SILVER, obj = Objs.ROCKS_2311),
    Rock(RockType.SILVER, obj = Objs.ROCKS_11948),
    Rock(RockType.SILVER, obj = Objs.ROCKS_11949),
    Rock(RockType.SILVER, obj = Objs.ROCKS_11950),
    Rock(RockType.SILVER, obj = Objs.ROCKS_37304),
    Rock(RockType.SILVER, obj = Objs.ROCKS_37306),
    Rock(RockType.GOLD, obj = Objs.ROCKS_11951),
    Rock(RockType.GOLD, obj = Objs.ROCKS_11952),
    Rock(RockType.GOLD, obj = Objs.ROCKS_11953),
    Rock(RockType.GOLD, obj = Objs.ROCKS_37310),
    Rock(RockType.GOLD, obj = Objs.ROCKS_37312),
    Rock(RockType.IRON, obj = Objs.ROCKS_11954),
    Rock(RockType.IRON, obj = Objs.ROCKS_11955),
    Rock(RockType.IRON, obj = Objs.ROCKS_11956),
    Rock(RockType.TIN, obj = Objs.ROCKS_11957),
    Rock(RockType.TIN, obj = Objs.ROCKS_11958),
    Rock(RockType.COPPER, obj = Objs.ROCKS_11959),
    Rock(RockType.COPPER, obj = Objs.ROCKS_11960),
    Rock(RockType.COPPER, obj = Objs.ROCKS_11961),
    Rock(RockType.COPPER, obj = Objs.ROCKS_11962),
    Rock(RockType.COAL, obj = Objs.ROCKS_11963),
    Rock(RockType.COAL, obj = Objs.ROCKS_11964),
    Rock(RockType.CLAY, obj = Objs.ROCKS_11556),
    Rock(RockType.RUNITE, obj = Objs.ROCKS_14859),
    Rock(RockType.RUNITE, obj = Objs.ROCKS_14860),
    Rock(RockType.CLAY, obj = Objs.ROCKS_15503),
    Rock(RockType.CLAY, obj = Objs.ROCKS_15504),
    Rock(RockType.CLAY, obj = Objs.ROCKS_15505),
)
ROCKS.forEach { rock ->
    on_obj_option(obj = rock.obj, option = 1) {
        val obj = player.getInteractingGameObj()
        player.queue {
            Mining.mineRock(this, obj, rock.type)
        }
    }
}