package gg.rsmod.plugins.content.npcs

import gg.rsmod.plugins.api.cfg.Npcs

object Constants {
    // Barrows Chest Pseudo-ID
    val BARROWS_CHEST_ID = 100000

    val BOSS_NPC_IDS: Set<Int> =
        linkedSetOf(
            BARROWS_CHEST_ID,
            Npcs.CHAOS_ELEMENTAL,
            Npcs.DAGANNOTH_REX,
            Npcs.DAGANNOTH_PRIME,
            Npcs.DAGANNOTH_SUPREME,
            Npcs.GIANT_MOLE,
            Npcs.KING_BLACK_DRAGON,
            Npcs.KALPHITE_QUEEN,
            Npcs.TZTOKJAD,
        )

    val SLAYER_NPC_IDS: Set<Int> =
        linkedSetOf(
            Npcs.CRAWLING_HAND,
            Npcs.CRAWLING_HAND_1649,
            Npcs.CRAWLING_HAND_1650,
            Npcs.CRAWLING_HAND_1651,
            Npcs.CRAWLING_HAND_1652,
            Npcs.CRAWLING_HAND_1653,
            Npcs.CRAWLING_HAND_1654,
            Npcs.CRAWLING_HAND_1655,
            Npcs.CRAWLING_HAND_1656,
            Npcs.CRAWLING_HAND_1657,
            Npcs.CAVE_BUG,
            Npcs.CAVE_CRAWLER,
            Npcs.CAVE_CRAWLER_1601,
            Npcs.CAVE_CRAWLER_1602,
            Npcs.CAVE_CRAWLER_1603,
            Npcs.BANSHEE,
            Npcs.CAVE_SLIME,
            Npcs.ROCKSLUG,
            Npcs.ROCKSLUG_1632,
            Npcs.DESERT_LIZARD,
            Npcs.DESERT_LIZARD_2805,
            Npcs.DESERT_LIZARD_2806,
            Npcs.COCKATRICE,
            Npcs.PYREFIEND,
            Npcs.PYREFIEND_1634,
            Npcs.PYREFIEND_1635,
            Npcs.PYREFIEND_1636,
            Npcs.MOGRE,
            Npcs.HARPIE_BUG_SWARM,
            Npcs.WALL_BEAST,
            Npcs.KILLERWATT,
            Npcs.KILLERWATT_3202,
            Npcs.BASILISK,
            Npcs.BASILISK_1617,
            Npcs.FEVER_SPIDER,
            Npcs.INFERNAL_MAGE,
            Npcs.INFERNAL_MAGE_1644,
            Npcs.INFERNAL_MAGE_1645,
            Npcs.INFERNAL_MAGE_1646,
            Npcs.INFERNAL_MAGE_1647,
            Npcs.JELLY,
            Npcs.JELLY_1638,
            Npcs.JELLY_1639,
            Npcs.JELLY_1640,
            Npcs.JELLY_1641,
            Npcs.JELLY_1642,
            Npcs.TUROTH,
            Npcs.TUROTH_1626,
            Npcs.TUROTH_1627,
            Npcs.TUROTH_1628,
            Npcs.TUROTH_1629,
            Npcs.TUROTH_1630,
            Npcs.ABERRANT_SPECTRE,
            Npcs.ABERRANT_SPECTRE_1605,
            Npcs.ABERRANT_SPECTRE_1606,
            Npcs.ABERRANT_SPECTRE_1607,
            Npcs.DUST_DEVIL,
            Npcs.KURASK,
            Npcs.KURASK_1609,
            Npcs.SKELETAL_WYVERN,
            Npcs.SKELETAL_WYVERN_3069,
            Npcs.SKELETAL_WYVERN_3070,
            Npcs.SKELETAL_WYVERN_3071,
            Npcs.GARGOYLE,
            Npcs.NECHRYAEL,
            Npcs.ABYSSAL_DEMON,
            Npcs.DARK_BEAST,
            Npcs.SMOKEDEVIL,
        )
}
