package gg.rsmod.plugins.content.items

import gg.rsmod.plugins.api.cfg.Items

enum class AncientArtifacts(val itemId: Int, val notedId: Int, val value: Int) {
    BROKEN_STATUE_HEADDRESS(Items.BROKEN_STATUE_HEADDRESS, Items.BROKEN_STATUE_HEADDRESS_NOTED, 5_000),
    THIRD_AGE_CARAFE(Items.THIRD_AGE_CARAFE, Items.THIRD_AGE_CARAFE_NOTED, 10_000),
    BRONZED_DRAGON_CLAW(Items.BRONZED_DRAGON_CLAW, Items.BRONZED_DRAGON_CLAW_NOTED, 20_000),
    ANCIENT_PSALTERY_BRIDGE(Items.ANCIENT_PSALTERY_BRIDGE, Items.ANCIENT_PSALTERY_BRIDGE_NOTED, 30_000),
    SARADOMIN_AMPHORA(Items.SARADOMIN_AMPHORA, Items.SARADOMIN_AMPHORA_NOTED, 40_000),
    BANDOS_SCRIMSHAW(Items.BANDOS_SCRIMSHAW, Items.BANDOS_SCRIMSHAW_NOTED, 50_000),
    SARADOMIN_CARVING(Items.SARADOMIN_CARVING, Items.SARADOMIN_CARVING_NOTED, 75_000),
    ZAMORAK_MEDALLION(Items.ZAMORAK_MEDALLION, Items.ZAMORAK_MEDALLION_NOTED, 100_000),
    ARMADYL_TOTEM(Items.ARMADYL_TOTEM, Items.ARMADYL_TOTEM_NOTED, 150_000),
    GUTHIXIAN_BRAZIER(Items.GUTHIXIAN_BRAZIER, Items.GUTHIXIAN_BRAZIER_NOTED, 200_000),
    RUBY_CHALICE(Items.RUBY_CHALICE, Items.RUBY_CHALICE_NOTED, 250_000),
    BANDOS_STATUETTE(Items.BANDOS_STATUETTE, Items.BANDOS_STATUETTE_NOTED, 300_000),
    SARADOMIN_STATUETTE(Items.SARADOMIN_STATUETTE, Items.SARADOMIN_STATUETTE_NOTED, 400_000),
    ZAMORAK_STATUETTE(Items.ZAMORAK_STATUETTE, Items.ZAMORAK_STATUETTE_NOTED, 500_000),
    ARMADYL_STATUETTE(Items.ARMADYL_STATUETTE, Items.ARMADYL_STATUETTE_NOTED, 750_000),
    SEREN_STATUETTE(Items.SEREN_STATUETTE, Items.SEREN_STATUETTE_NOTED, 1_000_000),
    ANCIENT_STATUETTE(Items.ANCIENT_STATUETTE, Items.ANCIENT_STATUETTE_NOTED, 5_000_000);

    companion object {
        fun unnotedItems(): List<Int> = AncientArtifacts.values().map { artefact -> artefact.itemId }
        fun notedItems(): List<Int> = AncientArtifacts.values().map { artefact -> artefact.notedId }
        fun forUnnoted(id: Int): AncientArtifacts? = AncientArtifacts.values().firstOrNull { artefact -> artefact
            .itemId == id }
    }
}
