package gg.rsmod.plugins.content.areas.alkharid

/**
 * @author Kevin Senez <ksenez94@gmail.com>
 */

spawn_npc(npc = Npcs.MAN_2, x = 3298, z = 3185, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.MAN_16, x = 3279, z = 3191, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3282, z = 3176, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3284, z = 3170, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3284, z = 3174, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3288, z = 3168, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3292, z = 3169, direction = Direction.WEST)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3295, z = 3168, direction = Direction.WEST)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3301, z = 3170, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3301, z = 3174, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ALKHARID_WARRIOR, x = 3301, z = 3177, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.SPIDER, x = 3321, z = 3145, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.SPIDER, x = 3322, z = 3143, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.SCORPION, x = 3275, z = 3154, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.FISHING_SPOT_FROGSPAWN, x = 3267, z = 3148, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.FISHING_SPOT_FROGSPAWN, x = 3276, z = 3140, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.FISHING_SPOT_FROGSPAWN, x = 3275, z = 3140, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BANKER_496, x = 3267, z = 3164, direction = Direction.EAST)
spawn_npc(npc = Npcs.BANKER_496, x = 3267, z = 3167, direction = Direction.EAST)
spawn_npc(npc = Npcs.BANKER_496, x = 3267, z = 3169, direction = Direction.EAST)
spawn_npc(npc = Npcs.BANKER_497, x = 3267, z = 3166, direction = Direction.EAST)
spawn_npc(npc = Npcs.BANKER_497, x = 3267, z = 3168, direction = Direction.EAST)
spawn_npc(npc = Npcs.SHOPKEEPER_524, x = 3316, z = 3184, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.SHOP_ASSISTANT_525, x = 3316, z = 3182, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.ZEKE, x = 3288, z = 3190, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.LOUIE_LEGS, x = 3316, z = 3175, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.KARIM, x = 3272, z = 3182, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.RANAEL, x = 3316, z = 3164, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.DOMMIK, x = 3322, z = 3195, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.HASSAN, x = 3302, z = 3163, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.OSMAN, x = 3286, z = 3180, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.AL_THE_CAMEL, x = 3274, z = 3168, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ELLIS, x = 3275, z = 3193, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.SORCERESS, x = 3323, z = 3138, height = 1, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.APPRENTICE_5532, x = 3320, z = 3138, walkRadius = 5, direction = Direction.WEST)