package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.ARIANWYN, x = 2352, z = 3172, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ARVEL, x = 2335, z = 3177, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.DALLDAV, x = 2324, z = 3164, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.EOIN, x = 2336, z = 3173, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ELF_WARRIOR_2359, x = 2329, z = 3171, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ELF_WARRIOR_2360, x = 2328, z = 3172, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ELF_WARRIOR_2361, x = 2345, z = 3175, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ELF_WARRIOR_2362, x = 2344, z = 3170, height = 1, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.EUDAV, x = 2334, z = 3182, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GETHIN, x = 2335, z = 3158, height = 1, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GOREU, x = 2337, z = 3159, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.IONA, x = 2335, z = 3169, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.AMAETHWR, x = 2347, z = 3164, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GWIR, x = 2352, z = 3179, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.MAWRTH, x = 2331, z = 3165, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ORONWEN, x = 2324, z = 3179, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TECLYN, x = 2344, z = 3163, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.YSGAWYN, x = 2343, z = 3169, height = 1, walkRadius = 5, direction = Direction.SOUTH)
