package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.REVENANT_IMP, x = 3120, z = 10135, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_DARK_BEAST, x = 3117, z = 10145, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_GOBLIN_13468, x = 3121, z = 10144, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_PYREFIEND, x = 3127, z = 10145, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_ORK, x = 3109, z = 10148, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_DEMON, x = 3116, z = 10155, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_DRAGON, x = 3116, z = 10165, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_VAMPYRE, x = 3107, z = 10164, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_HELLHOUND, x = 3103, z = 10167, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_HOBGOBLIN, x = 3101, z = 10169, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_GOBLIN_13469, x = 3095, z = 10152, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_ICEFIEND, x = 3097, z = 10156, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_GOBLIN, x = 3094, z = 10165, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_WEREWOLF, x = 3094, z = 10168, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_KNIGHT, x = 3091, z = 10150, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.REVENANT_IMP, x = 3088, z = 10162, walkRadius = 5, direction = Direction.NORTH)