package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.ANKOU, x = 2357, z = 5237, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU, x = 2358, z = 5237, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU, x = 2358, z = 5246, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU, x = 2359, z = 5241, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU, x = 2358, z = 5243, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU, x = 2359, z = 5242, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU, x = 2360, z = 5243, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU, x = 2361, z = 5241, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2332, z = 5193, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2331, z = 5195, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2329, z = 5198, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2326, z = 5196, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2331, z = 5203, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2324, z = 5200, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2323, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2323, z = 5202, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2324, z = 5208, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2318, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4382, x = 2329, z = 5209, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2320, z = 5217, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2320, z = 5224, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2322, z = 5228, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2322, z = 5230, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2321, z = 5231, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2327, z = 5225, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2327, z = 5228, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2327, z = 5230, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2320, z = 5224, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2321, z = 5232, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2324, z = 5236, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.ANKOU_4383, x = 2322, z = 5229, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ankou
spawn_npc(npc = Npcs.SKELETON_4384, x = 2355, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2353, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2350, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2357, z = 5196, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2324, z = 5197, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2329, z = 5206, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2329, z = 5208, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2356, z = 5200, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2354, z = 5197, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2345, z = 5198, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4384, x = 2352, z = 5195, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4385, x = 2351, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4385, x = 2353, z = 5201, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4385, x = 2332, z = 5203, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4385, x = 2328, z = 5204, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4385, x = 2352, z = 5201, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4385, x = 2350, z = 5198, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4386, x = 2313, z = 5191, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_4386, x = 2310, z = 5189, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.GHOST_4387, x = 2354, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4387, x = 2345, z = 5197, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4387, x = 2356, z = 5198, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4387, x = 2351, z = 5200, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4387, x = 2354, z = 5196, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2318, z = 5224, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2307, z = 5225, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2306, z = 5229, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2325, z = 5227, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2316, z = 5230, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2315, z = 5236, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2313, z = 5236, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2312, z = 5236, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2306, z = 5238, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2305, z = 5240, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2314, z = 5241, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_4388, x = 2306, z = 5243, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.SKELETON_5365, x = 2351, z = 5194, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5365, x = 2345, z = 5196, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5365, x = 2352, z = 5196, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5365, x = 2349, z = 5198, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5366, x = 2349, z = 5196, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5366, x = 2357, z = 5194, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5366, x = 2337, z = 5200, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5366, x = 2325, z = 5202, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5366, x = 2318, z = 5204, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5366, x = 2356, z = 5198, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5367, x = 2313, z = 5186, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.SKELETON_5368, x = 2308, z = 5188, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Skeleton
spawn_npc(npc = Npcs.GHOST_5369, x = 2353, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5369, x = 2322, z = 5219, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5369, x = 2317, z = 5225, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5369, x = 2324, z = 5234, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5369, x = 2350, z = 5203, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5369, x = 2351, z = 5195, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5370, x = 2353, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5370, x = 2359, z = 5194, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5370, x = 2319, z = 5220, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5370, x = 2319, z = 5226, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5370, x = 2326, z = 5224, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5370, x = 2355, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5370, x = 2352, z = 5198, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5371, x = 2350, z = 5199, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5371, x = 2319, z = 5224, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5371, x = 2314, z = 5225, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5371, x = 2325, z = 5228, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5371, x = 2354, z = 5201, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.GHOST_5371, x = 2354, z = 5198, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Ghost
spawn_npc(npc = Npcs.SHADE, x = 2355, z = 5216, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Shade
spawn_npc(npc = Npcs.SHADE, x = 2360, z = 5209, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Shade
spawn_npc(npc = Npcs.SHADE, x = 2358, z = 5213, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Shade
spawn_npc(npc = Npcs.SHADE, x = 2366, z = 5218, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Shade
spawn_npc(npc = Npcs.SHADE, x = 2360, z = 5218, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Shade
spawn_npc(npc = Npcs.SHADE, x = 2365, z = 5215, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Shade
