package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.DARK_BEAST, x = 1988, z = 4659, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1988, z = 4664, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1990, z = 4651, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1992, z = 4656, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1993, z = 4632, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1994, z = 4647, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1994, z = 4660, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1995, z = 4650, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1996, z = 4664, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1999, z = 4638, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2000, z = 4645, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2020, z = 4659, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2021, z = 4664, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2023, z = 4655, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2024, z = 4661, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2028, z = 4660, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2029, z = 4664, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2032, z = 4657, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 2033, z = 4662, walkRadius = 5, direction = Direction.NORTH)