package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.KURASK, x = 2693, z = 10001, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Kurask
spawn_npc(npc = Npcs.KURASK, x = 2703, z = 10001, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Kurask
spawn_npc(npc = Npcs.KURASK, x = 2701, z = 9996, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Kurask
spawn_npc(npc = Npcs.KURASK, x = 2700, z = 9990, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Kurask
spawn_npc(npc = Npcs.KURASK_1609, x = 2698, z = 9999, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Kurask
spawn_npc(npc = Npcs.BASILISK, x = 2739, z = 10009, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.BASILISK, x = 2736, z = 10014, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.BASILISK, x = 2745, z = 10001, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.BASILISK, x = 2741, z = 10012, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.BASILISK, x = 2742, z = 10003, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.BASILISK, x = 2745, z = 10021, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.BASILISK, x = 2745, z = 10005, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.BASILISK, x = 2743, z = 10013, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.BASILISK, x = 2747, z = 10015, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Basilisk
spawn_npc(npc = Npcs.TUROTH, x = 2718, z = 10008, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1626, x = 2726, z = 10003, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1626, x = 2722, z = 10006, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1626, x = 2724, z = 9997, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2728, z = 9999, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2727, z = 10005, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2726, z = 10008, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2720, z = 10014, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2722, z = 10013, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2716, z = 10009, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2719, z = 10007, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2719, z = 10000, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2719, z = 9997, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1627, x = 2726, z = 9994, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2726, z = 10012, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2726, z = 10009, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2729, z = 9999, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2727, z = 9994, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2730, z = 9996, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2726, z = 10011, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2726, z = 10009, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2725, z = 10014, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2729, z = 10010, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2717, z = 10008, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.TUROTH_1628, x = 2728, z = 10008, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Turoth
spawn_npc(npc = Npcs.JELLY, x = 2699, z = 10027, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1638, x = 2705, z = 10033, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1638, x = 2702, z = 10026, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1639, x = 2711, z = 10034, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1640, x = 2712, z = 10023, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1640, x = 2709, z = 10025, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1641, x = 2709, z = 10028, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1641, x = 2708, z = 10029, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1642, x = 2710, z = 10030, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.JELLY_1642, x = 2703, z = 10025, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Jelly
spawn_npc(npc = Npcs.AQUANITE, x = 2732, z = 9984, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Aquanite
