package gg.rsmod.plugins.content.areas.spawns

/**
 * @author Alycia <https://github.com/alycii>
 */

spawn_npc(npc = Npcs.HILL_GIANT, x = 2909, z = 9726, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2909, z = 9690, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2911, z = 9689, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2905, z = 9687, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2912, z = 9682, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2917, z = 9681, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2918, z = 9679, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2916, z = 9677, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2911, z = 9675, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2906, z = 9675, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2905, z = 9673, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2897, z = 9675, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2899, z = 9678, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2898, z = 9682, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2897, z = 9687, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2903, z = 9690, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2904, z = 9692, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2902, z = 9693, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2915, z = 9691, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2916, z = 9694, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2913, z = 9694, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2892, z = 9709, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2915, z = 9708, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2899, z = 9702, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLACK_KNIGHT, x = 2907, z = 9711, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.LORD_DAQUARIUS, x = 2891, z = 9680, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.DWARF_118, x = 2931, z = 9699, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.DWARF_118, x = 2930, z = 9703, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.VELRAK_THE_EXPLORER, x = 2931, z = 9685, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.JAILER, x = 2931, z = 9692, walkRadius = 5, direction = Direction.NORTH_WEST)
