package gg.rsmod.plugins.content.areas.spawns

/**
 * @author Alycia <https://github.com/alycii>
 */

spawn_npc(npc = Npcs.TZHAARMEJ, x = 2474, z = 5145, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.TZHAARMEJ_2592, x = 2461, z = 5142, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TZHAARMEJ_2596, x = 2483, z = 5155, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.TZHAARMEJ_2597, x = 2446, z = 5144, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.TZHAARMEJ_2597, x = 2470, z = 5141, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TZHAARHUR, x = 2485, z = 5159, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.TZHAARHUR, x = 2489, z = 5155, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.TZHAARHUR, x = 2471, z = 5144, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARHUR, x = 2476, z = 5153, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.TZHAARHUR, x = 2477, z = 5150, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2439, z = 5170, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2451, z = 5170, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2453, z = 5161, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2460, z = 5160, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2457, z = 5155, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2480, z = 5168, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2469, z = 5166, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2490, z = 5173, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2488, z = 5171, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2483, z = 5156, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2470, z = 5147, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2468, z = 5139, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2458, z = 5141, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2454, z = 5141, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2452, z = 5124, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2454, z = 5122, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2453, z = 5143, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL, x = 2443, z = 5144, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TZHAARXIL_2609, x = 2440, z = 5128, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL_2609, x = 2436, z = 5133, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARXIL_2609, x = 2450, z = 5168, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.TZHAARXIL_2609, x = 2443, z = 5170, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.TZHAARXIL_2609, x = 2445, z = 5177, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.TZHAARKET_2616, x = 2441, z = 5130, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.TZHAARKET_2616, x = 2438, z = 5135, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TZHAARKET_2616, x = 2443, z = 5138, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.TZHAARMEJJAL, x = 2440, z = 5168, direction = Direction.NORTH)
spawn_npc(npc = Npcs.TZHAARKETZUH, x = 2446, z = 5179, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TZHAARHURTEL, x = 2478, z = 5146, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.TZHAARHURLEK, x = 2464, z = 5149, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.TZHAARMEJROH, x = 2462, z = 5125, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.TZHAARMEJKAH, x = 2399, z = 5178, walkRadius = 5, direction = Direction.SOUTH)
