package gg.rsmod.plugins.content.areas.spawns

/**
 * @author RSDEANEO <https://github.com/RSDEANEO
 */

spawn_npc(npc = Npcs.CAVE_SLIME, x = 3209, z = 9556, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3208, z = 9587, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG, x = 3209, z = 9587, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3211, z = 9571, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG, x = 3210, z = 9587, walkRadius = 6, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_SLIME, x = 3210, z = 9556, walkRadius = 7, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_SLIME, x = 3210, z = 9571, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3211, z = 9588, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.HOLE_IN_THE_WALL, x = 3215, z = 9560, height = 0, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.HOLE_IN_THE_WALL, x = 3216, z = 9588, height = 0, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG, x = 3214, z = 9572, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GIANT_FROG, x = 3221, z = 9549, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BIG_FROG, x = 3221, z = 9559, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3220, z = 9558, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3222, z = 9568, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ROCKSLUG, x = 3223, z = 9570, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ROCKSLUG, x = 3220, z = 9579, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3224, z = 9585, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GIANT_FROG, x = 3224, z = 9545, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BIG_FROG, x = 3223, z = 9551, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BIG_FROG, x = 3222, z = 9558, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ROCKSLUG, x = 3224, z = 9578, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ROCKSLUG, x = 3224, z = 9582, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3226, z = 9570, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ROCKSLUG, x = 3225, z = 9573, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG, x = 3224, z = 9580, walkRadius = 7, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3227, z = 9580, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG, x = 3225, z = 9575, walkRadius = 7, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.GIANT_FROG, x = 3230, z = 9546, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3239, z = 9566, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3249, z = 9563, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BIG_FROG, x = 3243, z = 9569, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.FISHING_SPOT_5749, x = 3246, z = 9569, direction = Direction.SOUTH, static = true)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3241, z = 9575, walkRadius = 1, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3244, z = 9565, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_SLIME, x = 3251, z = 9569, walkRadius = 1, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_SLIME, x = 3250, z = 9572, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_GOBLIN, x = 3243, z = 9580, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_GOBLIN_1823, x = 3247, z = 9559, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BIG_FROG, x = 3247, z = 9567, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BIG_FROG, x = 3249, z = 9575, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3249, z = 9579, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_BUG_LARVA, x = 3250, z = 9567, walkRadius = 3, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_GOBLIN_1824, x = 3254, z = 9568, walkRadius = 2, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_SLIME, x = 3254, z = 9569, walkRadius = 4, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.CAVE_GOBLIN_1825, x = 3255, z = 9568, walkRadius = 1, direction = Direction.SOUTH)
