package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.ICE_GIANT, x = 3043, z = 9581, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ICE_GIANT, x = 3055, z = 9577, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ICE_GIANT, x = 3061, z = 9576, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.ICE_GIANT, x = 3055, z = 9571, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.ICE_GIANT, x = 3052, z = 9566, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3050, z = 9570, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3043, z = 9579, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3056, z = 9585, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3058, z = 9575, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3052, z = 9582, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3049, z = 9577, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3042, z = 9586, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3052, z = 9588, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3049, z = 9590, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3060, z = 9578, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.ICE_WARRIOR, x = 3054, z = 9566, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3062, z = 9550, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3050, z = 9554, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3048, z = 9545, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3061, z = 9542, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3065, z = 9548, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3034, z = 9544, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3033, z = 9552, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3029, z = 9545, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.SKELETAL_WYVERN, x = 3027, z = 9555, walkRadius = 5, direction = Direction.WEST)