package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.GREATER_DEMON_4699, x = 1623, z = 5252, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREATER_DEMON_4699, x = 1606, z = 5257, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREATER_DEMON_4698, x = 1624, z = 5258, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREATER_DEMON_4698, x = 1618, z = 5262, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREATER_DEMON_4700, x = 1612, z = 5260, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GREATER_DEMON_4700, x = 1617, z = 5252, walkRadius = 5, direction = Direction.NORTH)

spawn_npc(npc = Npcs.DARK_BEAST, x = 1653, z = 5299, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1657, z = 5296, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1649, z = 5294, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1647, z = 5288, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1656, z = 5287, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.DARK_BEAST, x = 1651, z = 5284, walkRadius = 5, direction = Direction.NORTH)

spawn_npc(npc = Npcs.HELLHOUND, x = 1658, z = 5257, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.HELLHOUND, x = 1653, z = 5257, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.HELLHOUND, x = 1641, z = 5256, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.HELLHOUND, x = 1652, z = 5255, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.HELLHOUND, x = 1646, z = 5253, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.HELLHOUND, x = 1648, z = 5257, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.HELLHOUND, x = 1637, z = 5255, walkRadius = 5, direction = Direction.NORTH)

spawn_npc(npc = Npcs.IRON_DRAGON, x = 1649, z = 5275, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.IRON_DRAGON, x = 1654, z = 5267, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.IRON_DRAGON, x = 1648, z = 5268, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.IRON_DRAGON, x = 1643, z = 5277, walkRadius = 5, direction = Direction.NORTH)

spawn_npc(npc = Npcs.STEEL_DRAGON, x = 1633, z = 5279, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.STEEL_DRAGON, x = 1625, z = 5279, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.STEEL_DRAGON, x = 1628, z = 5285, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.STEEL_DRAGON, x = 1637, z = 5282, walkRadius = 5, direction = Direction.NORTH)

spawn_npc(npc = Npcs.BLUE_DRAGON, x = 1605, z = 5269, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON_4681, x = 1611, z = 5273, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON_4682, x = 1608, z = 5277, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON_4683, x = 1606, z = 5283, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.BLUE_DRAGON_4684, x = 1612, z = 5281, walkRadius = 5, direction = Direction.NORTH)

spawn_npc(npc = Npcs.GARGOYLE, x = 1606, z = 5294, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GARGOYLE, x = 1607, z = 5301, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GARGOYLE, x = 1607, z = 5306, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GARGOYLE, x = 1615, z = 5303, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GARGOYLE, x = 1619, z = 5298, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GARGOYLE, x = 1613, z = 5294, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GARGOYLE, x = 1610, z = 5298, walkRadius = 5, direction = Direction.NORTH)

spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1630, z = 5306, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1631, z = 5299, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1636, z = 5298, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1640, z = 5299, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1643, z = 5297, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1646, z = 5307, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1643, z = 5305, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1638, z = 5307, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.ABYSSAL_DEMON, x = 1634, z = 5304, walkRadius = 5, direction = Direction.NORTH)