package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.JOGRE, x = 2835, z = 9526, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.JOGRE, x = 2832, z = 9514, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.JOGRE, x = 2825, z = 9521, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.JOGRE, x = 2846, z = 9520, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2838, z = 9508, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.JOGRE, x = 2832, z = 9495, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2838, z = 9492, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2851, z = 9485, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2847, z = 9481, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2865, z = 9494, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2855, z = 9502, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.JOGRE, x = 2870, z = 9496, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.JOGRE, x = 2851, z = 9511, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.JOGRE, x = 2853, z = 9519, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2857, z = 9520, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2863, z = 9525, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.JOGRE, x = 2869, z = 9530, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.JOGRE, x = 2865, z = 9515, walkRadius = 5, direction = Direction.NORTH_EAST)
spawn_npc(npc = Npcs.JOGRE, x = 2868, z = 9507, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.JOGRE, x = 2874, z = 9512, walkRadius = 5, direction = Direction.SOUTH_WEST)
