package gg.rsmod.plugins.content.areas.spawns

/**
 * @author Alycia <https://github.com/alycii>
 */
spawn_npc(npc = Npcs.MAN, x = 2712, z = 3484, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.MAN, x = 2693, z = 3495, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.MAN_2, x = 2690, z = 3489, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.MAN_3, x = 2699, z = 3491, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.WOMAN_BRUNETTE_LONGSKIRT_4, x = 2693, z = 3493, walkRadius = 5, direction = Direction.SOUTH_EAST)
spawn_npc(npc = Npcs.WOMAN_BRUNETTE_LONGSKIRT_4, x = 2693, z = 3492, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.WOMAN_BRUNETTE_LONGSKIRT_4, x = 2695, z = 3497, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.WOMAN_BRUNETTE_LONGSKIRT_4, x = 2700, z = 3496, walkRadius = 5, direction = Direction.SOUTH_WEST)
spawn_npc(npc = Npcs.WOMAN_BRUNETTE_PONYTAIL_5, x = 2697, z = 3493, walkRadius = 5, direction = Direction.EAST)
spawn_npc(npc = Npcs.HIGHWAYMAN, x = 2744, z = 3519, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.SEER, x = 2709, z = 3485, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.SEER, x = 2716, z = 3475, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.SEER, x = 2697, z = 3472, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.SEER, x = 2702, z = 3469, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.IMP, x = 2733, z = 3459, walkRadius = 5, direction = Direction.WEST)
spawn_npc(npc = Npcs.IMP, x = 2732, z = 3457, walkRadius = 5, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BARTENDER_738, x = 2691, z = 3492, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.GUARD_812, x = 2738, z = 3473, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.GUARD_812, x = 2733, z = 3473, walkRadius = 5, direction = Direction.NORTH)
spawn_npc(npc = Npcs.POISON_SALESMAN, x = 2697, z = 3496, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.PHANTUWTI_FANSTUWI_FARSIGHT, x = 2701, z = 3471, walkRadius = 5, direction = Direction.NORTH_WEST)
spawn_npc(npc = Npcs.BANKER_SPECIAL_MALE_2568, x = 2729, z = 3495, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BANKER_SPECIAL_MALE_2568, x = 2724, z = 3495, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BANKER_SPECIAL_MALE_2568, x = 2727, z = 3495, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.BANKER_SPECIAL_MALE_2568, x = 2722, z = 3495, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.ESTATE_AGENT, x = 2737, z = 3500, walkRadius = 1, direction = Direction.SOUTH)
spawn_npc(npc = Npcs.TOWN_CRIER_6139, x = 2734, z = 3484, walkRadius = 5, direction = Direction.NORTH)
