package gg.rsmod.plugins.content.areas.spawns

spawn_npc(npc = Npcs.DARK_MAGE_2262, x = 3039, z = 4834, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Dark mage
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3018, z = 4832, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3019, z = 4846, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3022, z = 4847, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3021, z = 4851, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3037, z = 4855, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3022, z = 4848, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3035, z = 4853, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3032, z = 4855, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3043, z = 4852, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3016, z = 4840, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3013, z = 4829, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3015, z = 4834, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3014, z = 4839, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3014, z = 4838, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3014, z = 4840, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3018, z = 4824, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3016, z = 4824, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3019, z = 4820, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3016, z = 4815, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3021, z = 4815, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3016, z = 4816, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3042, z = 4809, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3025, z = 4807, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3055, z = 4813, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3059, z = 4816, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3062, z = 4838, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3059, z = 4838, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3066, z = 4822, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3048, z = 4850, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3057, z = 4851, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_LEECH, x = 3053, z = 4857, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal leech
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3019, z = 4842, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3041, z = 4854, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3045, z = 4853, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3016, z = 4827, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3030, z = 4807, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3056, z = 4815, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3059, z = 4817, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3060, z = 4809, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3062, z = 4813, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3063, z = 4822, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3062, z = 4839, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3059, z = 4837, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3064, z = 4840, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3065, z = 4827, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3065, z = 4830, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_GUARDIAN, x = 3065, z = 4839, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal guardian
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3017, z = 4830, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3023, z = 4846, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3029, z = 4857, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3015, z = 4825, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3019, z = 4818, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3024, z = 4815, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3023, z = 4811, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3026, z = 4812, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3031, z = 4812, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3035, z = 4811, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3043, z = 4809, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3044, z = 4812, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3031, z = 4807, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3027, z = 4808, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3030, z = 4808, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3039, z = 4807, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3038, z = 4808, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3036, z = 4808, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3024, z = 4806, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3047, z = 4810, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3047, z = 4811, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3052, z = 4814, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3052, z = 4813, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3055, z = 4812, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3057, z = 4817, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3057, z = 4816, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3059, z = 4813, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3059, z = 4812, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3058, z = 4817, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3059, z = 4812, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3061, z = 4828, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3060, z = 4825, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3060, z = 4841, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
spawn_npc(npc = Npcs.ABYSSAL_WALKER, x = 3048, z = 4855, height = 0, walkRadius = 5, direction = Direction.NORTH, static = false) //Abyssal walker
