package gg.rsmod.game.model.combat

/**
 * @author Alycia <https://github.com/alycii>
 */
enum class SlayerAssignment(
    val identifier: String,
) {
    ANKOU("Ankous"),
    ABERRANT_SPECTRE("Aberrant spectres"),
    ABYSSAL_DEMON("Abyssal Demons"),
    BIRD("Birds"),
    BANSHEE("Banshees"),
    BEAR("Bears"),
    BLACK_DRAGON("Black Dragons"),
    BLOODVELD("Bloodvelds"),
    CAVE_BUG("Cave Bugs"),
    CAVE_SLIME("Cave Slimes"),
    CAVE_CRAWLER("Cave Crawlers"),
    CRAWLING_HAND("Crawling Hands"),
    COCKATRICE("Cockatrice"),
    DESERT_LIZARD("Desert Lizards"),
    DOG("Dogs"),
    DWARF("Dwarves"),
    FLESH_CRAWLER("Flesh Crawlers"),
    GREATER_DEMON("Greater Demons"),
    GARGOYLE("Gargoyles"),
    GREEN_DRAGON("Green Dragons"),
    GHOST("Ghosts"),
    GHOUL("Ghouls"),
    GOBLIN("Goblins"),
    HILL_GIANT("Hill Giants"),
    CATABLEPON("Catablepons"),
    ICEFIEND("Icefiends"),
    INFERNAL_MAGE("Infernal mages"),
    LESSER_DEMON("Lesser Demons"),
    MINOTAUR("Minotaurs"),
    MOSS_GIANT("Moss Giants"),
    MONKEY("Monkeys"),
    NECHRYAEL("Nechryaels"),
    PYREFIEND("Pyrefiends"),
    ROCK_SLUG("Rockslugs"),
    SCORPION("Scorpions"),
    SKELETON("Skeletons"),
    SHADE("Shades"),
    SPIDER("Spiders"),
    WOLF("Wolves"),
    HELLHOUNDS("Hellhounds"),
    ZOMBIE("Zombies"),
    BAT("Bats"),
    COW("Cows"),
    ICE_WARRIOR("Ice Warriors"),
    ICE_GIANT("Ice Giants"),
}
